In [1]:
import re

In [2]:
import csv

In [3]:
import numpy as np

In [4]:
import pandas as pd

## Loading Files

In [5]:
jan = pd.read_csv('CASH Sales Audit Report by Dept Jan22.csv',sep=',', header=None, engine='python' )

In [6]:
feb = pd.read_csv('CASH Sales Audit Report by Dept Feb22.csv',sep=',', header=None, engine='python' )

In [7]:
mar = pd.read_csv('CASH Sales Audit Report by Dept Mar22.csv',sep=',', header=None, engine='python' )

In [8]:
apr = pd.read_csv('CASH Sales Audit Report by Dept Apr22.csv',sep=',', header=None, engine='python' )

In [9]:
may = pd.read_csv('CASH Sales Audit Report by Dept May22.csv',sep=',', header=None, engine='python' )

In [10]:
jun = pd.read_csv('CASH Sales Audit Report by Dept Jun22.csv',sep=',', header=None, engine='python' )

In [11]:
jul = pd.read_csv('CASH Sales Audit Report by Dept Jul22.csv',sep=',', header=None, engine='python' )

In [12]:
aug = pd.read_csv('CASH Sales Audit Report by Dept Aug22.csv',sep=',', header=None, engine='python' )

In [13]:
sep = pd.read_csv('CASH Sales Audit Report by Dept Sep22.csv',sep=',', header=None, engine='python' )

In [14]:
october = pd.read_csv('CASH Sales Audit Report by Dept Oct22.csv',sep=',', header=None, engine='python' )

In [15]:
nov = pd.read_csv('CASH Sales Audit Report by Dept Nov22.csv',sep=',', header=None, engine='python' )

In [16]:
dec = pd.read_csv('CASH Sales Audit Report by Dept Dec22.csv',sep=',', header=None, engine='python' )

## Concatenating DataFrames

In [17]:
year_2022 = pd.concat([jan,feb,mar,apr,may,jun,jul,aug,sep,october,nov,dec])

In [18]:
year_2022.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 86218 entries, 0 to 5774
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       86218 non-null  object
 1   1       86218 non-null  object
 2   2       86206 non-null  object
 3   3       86206 non-null  object
 4   4       85837 non-null  object
 5   5       85837 non-null  object
 6   6       82782 non-null  object
dtypes: object(7)
memory usage: 5.3+ MB

## Preparing FIle / Column Names

In [19]:
mapper = ({0:'Date',
           1:'Invoice',
           2:'SKU',
           3:'Name',
           4:'Quantity',
           5:'UOM',
           6:'Total'})

In [20]:
year_2022 = year_2022.rename(columns=mapper)

In [35]:
year_2022.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85837 entries, 0 to 5773
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      85837 non-null  datetime64[ns]
 1   Invoice   85837 non-null  object
 2   SKU       85837 non-null  object
 3   Name      85837 non-null  object
 4   Quantity  85837 non-null  object
 5   UOM       85837 non-null  object
 6   Total     75783 non-null  object
dtypes: datetime64[ns](1), object(6)
memory usage: 5.2+ MB

## Cleaning File

In [22]:
year_2022 = year_2022[year_2022.UOM.notnull()]

In [196]:
year_2022['Total'] = year_2022['Total'].str.replace('\r\n', '')

In [24]:
year_2022['Total'] = year_2022['Total'].str.replace(',', '')

## Setting DataTypes

In [25]:
year_2022['Date'] = pd.to_datetime(year_2022['Date'])

In [50]:
year_2022[163:164]['Total'] = year_2022[163:164]['UOM']

C:\Users\NewHome32\AppData\Local\Temp/ipykernel_3448/332658954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022[163:164]['Total'] = year_2022[163:164]['UOM']

In [62]:
year_2022.head()

,Date,Invoice,SKU,Name,Quantity,UOM,Total
0,2022-01-29,40673B,FB24Z,ZMAX FENCE BRACKET,12.000,EACH,16.68
2,2022-01-29,40458A,01-KV208WH5,"20"" BRACKET WHITE REINFORCED 50",2.000,EACH,29.98
3,2022-01-24,38339A,120500,GREEN GLUE SEALANT,2.000,EACH,39.98
4,2022-01-22,38066A,1212GYPROC,"1/2"" GYPROC 1/2SHT",1.000,EACH,10.99
5,2022-01-24,38500B,1212GYPROC,"1/2"" GYPROC 1/2SHT",1.000,EACH,10.99

## Need to figure out how to clean this in a smart way

In [58]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace='1.000- BAG',value=1)

In [89]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace=' 2.000- PIECE',value=2)

In [94]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace=' 1.000- PIECE',value=1)

In [91]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace=' 5.000- PIECE',value=5)

In [84]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace=' 10.000- BAG',value=10)

In [96]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace=' 47.000- PIECE',value=47)

In [98]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace='1.000- EACH',value=1)

In [100]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace=' 1.000- EACH',value=1)

In [102]:
year_2022['Quantity'] = year_2022['Quantity'].replace(to_replace='16.000- EACH',value=16)

In [135]:
year_2022['Quantity'] = year_2022['Quantity'].str.strip()

In [187]:
year_2022[465:466]

,Date,Invoice,SKU,Name,Quantity,UOM,Total
475,2022-01-11,33828B,2410S,2x4-10'KDSPF 2BTR PREMIUM,4.000- PIECE,43.33-\r\n,None

In [17]:
to_replace = []

year_2022['Quantity']= year_2022['Quantity'].astype(str)

for item in year_2022['Quantity'].unique():
    
    if len(item) > 7:
        to_replace.append(item)

In [192]:
bool_series = pd.isnull(year_2022['Total'])

In [195]:
for item in year_2022[bool_series]:
    year_2022['Total'] = year_2022['UOM']

,Date,Invoice,SKU,Name,Quantity,UOM,Total
161,2022-01-19,36614B,CONC,CEM CONCRETE MIX 55LB,10,67.50-\r\n,67.50-\r\n
274,2022-01-13,34781B,128CGC,1x2-8' CLEAR GREEN CEDAR,2,12.26-\r\n,12.26-\r\n
279,2022-01-28,40126B,128CGC,1x2-8' CLEAR GREEN CEDAR,5,30.66-\r\n,30.66-\r\n
281,2022-01-13,34781B,148RC,1x4-8' ROUGH CUT CEDAR,1,9.69-\r\n,9.69-\r\n
286,2022-01-28,40126B,166RC,1x6-6' RC S1S2E,47,421.59-\r\n,421.59-\r\n
...,...,...,...,...,...,...,...
5707,2022-12-03,69836B,523136,PL PREMIUM ADHESIVE 825ML,3.000- EACH,59.97-\r\n,59.97-\r\n
5724,2022-12-29,77997B,DUST135,SYNKO DUST CONTROL 13.5L,1,38.99-\r\n,38.99-\r\n
5729,2022-12-23,77213B,HGAM10KTA,HURRICANE TIE 10PK W/CONC SCREW,1,83.24-\r\n,83.24-\r\n
5765,2022-12-20,76252B,48251002,"SELFEED MILWAUKEE BIT 1""",1,37.49-\r\n,37.49-\r\n
5766,2022-12-06,70605B,591044,25g CREME HARDNER,1.000,1.46\r\n,1.46\r\n

In [199]:
year_2022[bool_series]

,Date,Invoice,SKU,Name,Quantity,UOM,Total
161,2022-01-19,36614B,CONC,CEM CONCRETE MIX 55LB,10,67.50-\r\n,67.50
274,2022-01-13,34781B,128CGC,1x2-8' CLEAR GREEN CEDAR,2,12.26-\r\n,12.26
279,2022-01-28,40126B,128CGC,1x2-8' CLEAR GREEN CEDAR,5,30.66-\r\n,30.66
281,2022-01-13,34781B,148RC,1x4-8' ROUGH CUT CEDAR,1,9.69-\r\n,9.69
286,2022-01-28,40126B,166RC,1x6-6' RC S1S2E,47,421.59-\r\n,421.59
...,...,...,...,...,...,...,...
5707,2022-12-03,69836B,523136,PL PREMIUM ADHESIVE 825ML,3.000- EACH,59.97-\r\n,59.97
5724,2022-12-29,77997B,DUST135,SYNKO DUST CONTROL 13.5L,1,38.99-\r\n,38.99
5729,2022-12-23,77213B,HGAM10KTA,HURRICANE TIE 10PK W/CONC SCREW,1,83.24-\r\n,83.24
5765,2022-12-20,76252B,48251002,"SELFEED MILWAUKEE BIT 1""",1,37.49-\r\n,37.49
5766,2022-12-06,70605B,591044,25g CREME HARDNER,1.000,1.46\r\n,1.46

In [198]:
year_2022['Total'] = year_2022['Total'].str.replace('-', '')

In [18]:
to_replace

['4.000- PIECE',
 '1.000- PIECE',
 '10.000- PIECE',
 '1.000- SHEET',
 '2.000- EACH',
 '2.000- SHEET',
 '3.000- EACH',
 '4.000- EACH',
 '35.000- PC',
 '0.800- EACH',
 '0.930- KG',
 '7.050- KG',
 '0.170- KG',
 '0.745- KG',
 '2.390- KG',
 '1.590- EACH',
 '0.250- KG',
 '0.520- KILO',
 '0.560- KILO',
 '5.790- KG',
 '0.060- KILO',
 '0.030- KILO',
 '6.000- EACH',
 '36.000- LF',
 '1.000- BOX',
 '2.000- BAG',
 '1.000- LF',
 '23.000- PIECE',
 '3.000- PIECE',
 '15.000- EACH',
 '207.000- EACH',
 '4.000- PC',
 '5.000- EACH',
 '0.045- EACH',
 '1.040- EACH',
 '1.000- ROLL',
 '0.560- EACH',
 '8.000- EACH',
 '0.460- EACH',
 '0.570- KG',
 '1.070- KG',
 '1.660- KG',
 '2.000- KG',
 '2.230- KG',
 '0.860- KG',
 '2.770- KG',
 '0.575- KG',
 '2.065- EACH',
 '1.010- EACH',
 '0.005- KILO',
 '0.360- KILO',
 '4.000- LFT',
 '2.000- PIECE',
 '12.000- PIECE',
 '7.000- PIECE',
 '6.000- PIECE',
 '30.000- EACH',
 '7.000- EACH',
 '28.000- EACH',
 '17.000- EACH',
 '0.055- EA',
 '23.000- EACH',
 '1.000- TUBE',
 '0.405- EACH',
 '0.885- KG',
 '0.150- KG',
 '1.630- KG',
 '0.750- KILO',
 '1.300- EACH',
 '2.000- BOX',
 '0.015- KILO',
 '0.335- KILO',
 '0.055- EACH',
 '10.000- LFT',
 '0.200- EACH',
 '8.000- BAG',
 '5.000- BAG',
 '0.500- EACH',
 '5.000- PIECE',
 '1,224.000',
 '96.000- EACH',
 '3.000- SHEET',
 '12.000- EACH',
 '1.000- PC',
 '9.000- EACH',
 '1.000- FT',
 '0.185- KG',
 '0.525- KG',
 '1.830- KG',
 '3.040- KG',
 '1.450- KG',
 '1.990- KG',
 '0.080- KG',
 '0.190- EACH',
 '1.200- EACH',
 '1.000- BAG',
 '3.000- BAG',
 '16.000- PIECE',
 '10.000- SHEET',
 '21.000- LF',
 '4.000- LF',
 '2,000.000',
 '1,000.000',
 '0.145- EACH',
 '10.000- EACH',
 '24.000- EACH',
 '15.000- PC',
 '5.000- PC',
 '0.140- KG',
 '14.000- EACH',
 '0.415- KG',
 '0.515- KG',
 '0.335- KG',
 '1.010- KG',
 '0.320- KILO',
 '0.545- KG',
 '0.630- KILO',
 '0.285- KILO',
 '20.000- EACH',
 '6,000.000',
 '16.000- LF',
 '28.000- LF',
 '31.000- LF',
 '50.000- LF',
 '8.000- LF',
 '1,200.000',
 '1,200.000- EACH',
 '250.000- LF',
 '0.005- EACH',
 '2.250- KG',
 '3.755- KG',
 '0.700- EACH',
 '0.315- EACH',
 '1.320- EACH',
 '0.600- EACH',
 '0.090- KILO',
 '1,320.000',
 '1,300.000',
 '4.000- BAG',
 '6.000- BAG',
 '9.000- PIECE',
 '4.500- EACH',
 '264.000- LF',
 '33.000- EACH',
 '3.325- EACH',
 '0.835- KG',
 '0.145- KG',
 '1.665- EACH',
 '2.380- EACH',
 '1.360- KG',
 '1.310- EACH',
 '0.905- EACH',
 '0.140- KILO',
 '100.000- EACH',
 '1.000- BNDL',
 '13.000- EACH',
 '14.000- LF',
 '60.000- EACH',
 '4.000- SHEET',
 '0.050- EACH',
 '14.000- PC',
 '0.015- EACH',
 '0.085- KG',
 '1.570- KG',
 '0.385- KG',
 '0.985- KG',
 '0.150- KILO',
 '0.830- KG',
 '0.290- EACH',
 '0.230- EACH',
 '0.045- KILO',
 '0.135- KILO',
 '0.303- KILO',
 '0.058- KILO',
 '61.000- PIECE',
 '13.000- PIECE',
 '6.000- LF',
 '2,500.000',
 '335.000- EACH',
 '18.000- EACH',
 '24.000- PC',
 '0.170- EACH',
 '8.000- TUBE',
 '5.208- KG',
 '0.805- KG',
 '2.465- KG',
 '1.120- KG',
 '0.950- KG',
 '0.400- KILO',
 '0.330- EACH',
 '0.320- EACH',
 '0.420- EACH',
 '0.875- EACH',
 '0.110- KILO',
 '0.080- KILO',
 '0.050- KILO',
 '0.050- KG',
 '30.000- LFT',
 '7.000- BAG',
 '18.000- PIECE',
 '12.000- LF',
 '2.000- PC',
 '0.250- EACH',
 '0.530- KG',
 '0.720- KG',
 '0.535- KG',
 '0.415- KILO',
 '12.000- LFT',
 '8.000- LFT',
 '1,500.000',
 '16.000- BAG',
 '1.500- EACH',
 '16.000- FOOT',
 '64.000- LF',
 '24.000- LF',
 '10.000- PC',
 '0.105- KG',
 '4.430- KG',
 '1.000- KG',
 '1.280- KG',
 '0.680- KG',
 '0.070- KG',
 '1.340- KG',
 '0.175- EACH',
 '0.450- EACH',
 '0.040- KILO',
 '2.000- ROLL',
 '19.000- EACH',
 '25.000- EACH',
 '26.000- LF',
 '0.780- EACH',
 '2.590- KG',
 '0.035- KILO',
 '0.220- KILO',
 '50.000- LFT']

In [131]:
final = []
for item in to_replace:
    if len(item) > 7 and '-' not in item:
        final.append(item)

In [20]:
for item in to_replace:
    if len(item) > 7 and '-' in item:
        print(item)

4.000- PIECE
1.000- PIECE
10.000- PIECE
1.000- SHEET
2.000- EACH
2.000- SHEET
3.000- EACH
4.000- EACH
35.000- PC
0.800- EACH
0.930- KG
7.050- KG
0.170- KG
0.745- KG
2.390- KG
1.590- EACH
0.250- KG
0.520- KILO
0.560- KILO
5.790- KG
0.060- KILO
0.030- KILO
6.000- EACH
36.000- LF
1.000- BOX
2.000- BAG
1.000- LF
23.000- PIECE
3.000- PIECE
15.000- EACH
207.000- EACH
4.000- PC
5.000- EACH
0.045- EACH
1.040- EACH
1.000- ROLL
0.560- EACH
8.000- EACH
0.460- EACH
0.570- KG
1.070- KG
1.660- KG
2.000- KG
2.230- KG
0.860- KG
2.770- KG
0.575- KG
2.065- EACH
1.010- EACH
0.005- KILO
0.360- KILO
4.000- LFT
2.000- PIECE
12.000- PIECE
7.000- PIECE
6.000- PIECE
30.000- EACH
7.000- EACH
28.000- EACH
17.000- EACH
0.055- EA
23.000- EACH
1.000- TUBE
0.405- EACH
0.885- KG
0.150- KG
1.630- KG
0.750- KILO
1.300- EACH
2.000- BOX
0.015- KILO
0.335- KILO
0.055- EACH
10.000- LFT
0.200- EACH
8.000- BAG
5.000- BAG
0.500- EACH
5.000- PIECE
96.000- EACH
3.000- SHEET
12.000- EACH
1.000- PC
9.000- EACH
1.000- FT
0.185- KG
0.525- KG
1.830- KG
3.040- KG
1.450- KG
1.990- KG
0.080- KG
0.190- EACH
1.200- EACH
1.000- BAG
3.000- BAG
16.000- PIECE
10.000- SHEET
21.000- LF
4.000- LF
0.145- EACH
10.000- EACH
24.000- EACH
15.000- PC
5.000- PC
0.140- KG
14.000- EACH
0.415- KG
0.515- KG
0.335- KG
1.010- KG
0.320- KILO
0.545- KG
0.630- KILO
0.285- KILO
20.000- EACH
16.000- LF
28.000- LF
31.000- LF
50.000- LF
8.000- LF
1,200.000- EACH
250.000- LF
0.005- EACH
2.250- KG
3.755- KG
0.700- EACH
0.315- EACH
1.320- EACH
0.600- EACH
0.090- KILO
4.000- BAG
6.000- BAG
9.000- PIECE
4.500- EACH
264.000- LF
33.000- EACH
3.325- EACH
0.835- KG
0.145- KG
1.665- EACH
2.380- EACH
1.360- KG
1.310- EACH
0.905- EACH
0.140- KILO
100.000- EACH
1.000- BNDL
13.000- EACH
14.000- LF
60.000- EACH
4.000- SHEET
0.050- EACH
14.000- PC
0.015- EACH
0.085- KG
1.570- KG
0.385- KG
0.985- KG
0.150- KILO
0.830- KG
0.290- EACH
0.230- EACH
0.045- KILO
0.135- KILO
0.303- KILO
0.058- KILO
61.000- PIECE
13.000- PIECE
6.000- LF
335.000- EACH
18.000- EACH
24.000- PC
0.170- EACH
8.000- TUBE
5.208- KG
0.805- KG
2.465- KG
1.120- KG
0.950- KG
0.400- KILO
0.330- EACH
0.320- EACH
0.420- EACH
0.875- EACH
0.110- KILO
0.080- KILO
0.050- KILO
0.050- KG
30.000- LFT
7.000- BAG
18.000- PIECE
12.000- LF
2.000- PC
0.250- EACH
0.530- KG
0.720- KG
0.535- KG
0.415- KILO
12.000- LFT
8.000- LFT
16.000- BAG
1.500- EACH
16.000- FOOT
64.000- LF
24.000- LF
10.000- PC
0.105- KG
4.430- KG
1.000- KG
1.280- KG
0.680- KG
0.070- KG
1.340- KG
0.175- EACH
0.450- EACH
0.040- KILO
2.000- ROLL
19.000- EACH
25.000- EACH
26.000- LF
0.780- EACH
2.590- KG
0.035- KILO
0.220- KILO
50.000- LFT

In [16]:
year_2022['Quantity'] = pd.to_numeric(year_2022['Quantity'])

ValueError: Unable to parse string "4.000- PIECE" at position 465

In [30]:
year_2022['Total'] = pd.to_numeric(year_2022['Total'])

In [31]:
year_2022.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85837 entries, 0 to 5773
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      85837 non-null  datetime64[ns]
 1   Invoice   85837 non-null  object
 2   SKU       85837 non-null  object
 3   Name      85837 non-null  object
 4   Quantity  85837 non-null  object
 5   UOM       85837 non-null  object
 6   Total     75783 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 5.2+ MB

## Saving for later...

In [201]:
year_2022.to_csv(path_or_buf="CASH Sales Audit Report by Dept 2022.csv",encoding='Utf-8')

## Reloading...

In [5]:
year_2022 = pd.read_csv("CASH Sales Audit Report by Dept 2022.csv",encoding='Utf-8')

In [7]:
year_2022.head()

,Date,Invoice,SKU,Name,Quantity,UOM,Total
0,2022-01-29,40673B,FB24Z,ZMAX FENCE BRACKET,12.000,EACH,EACH
1,2022-01-29,40458A,01-KV208WH5,"20"" BRACKET WHITE REINFORCED 50",2.000,EACH,EACH
2,2022-01-24,38339A,120500,GREEN GLUE SEALANT,2.000,EACH,EACH
3,2022-01-22,38066A,1212GYPROC,"1/2"" GYPROC 1/2SHT",1.000,EACH,EACH
4,2022-01-24,38500B,1212GYPROC,"1/2"" GYPROC 1/2SHT",1.000,EACH,EACH

In [6]:
year_2022.drop('Unnamed: 0',axis=1,inplace=True)

In [17]:
to_replace = []

year_2022['Quantity'] = year_2022['Quantity'].astype(str)

for item in year_2022['Quantity'].unique():
    
    if '-' in item:
        to_replace.append(item)

In [18]:
to_replace

['4.000- PIECE',
 '1.000- PIECE',
 '10.000- PIECE',
 '1.000- SHEET',
 '2.000- EACH',
 '2.000- SHEET',
 '3.000- EACH',
 '4.000- EACH',
 '35.000- PC',
 '0.800- EACH',
 '0.930- KG',
 '7.050- KG',
 '0.170- KG',
 '0.745- KG',
 '2.390- KG',
 '1.590- EACH',
 '0.250- KG',
 '0.520- KILO',
 '0.560- KILO',
 '5.790- KG',
 '0.060- KILO',
 '0.030- KILO',
 '6.000- EACH',
 '36.000- LF',
 '1.000- BOX',
 '2.000- BAG',
 '1.000- LF',
 '23.000- PIECE',
 '3.000- PIECE',
 '15.000- EACH',
 '207.000- EACH',
 '4.000- PC',
 '5.000- EACH',
 '0.045- EACH',
 '1.040- EACH',
 '1.000- ROLL',
 '0.560- EACH',
 '8.000- EACH',
 '0.460- EACH',
 '0.570- KG',
 '1.070- KG',
 '1.660- KG',
 '2.000- KG',
 '2.230- KG',
 '0.860- KG',
 '2.770- KG',
 '0.575- KG',
 '2.065- EACH',
 '1.010- EACH',
 '0.005- KILO',
 '0.360- KILO',
 '4.000- LFT',
 '2.000- PIECE',
 '12.000- PIECE',
 '7.000- PIECE',
 '6.000- PIECE',
 '30.000- EACH',
 '7.000- EACH',
 '28.000- EACH',
 '17.000- EACH',
 '0.055- EA',
 '23.000- EACH',
 '1.000- TUBE',
 '0.405- EACH',
 '0.885- KG',
 '0.150- KG',
 '1.630- KG',
 '0.750- KILO',
 '1.300- EACH',
 '2.000- BOX',
 '0.015- KILO',
 '0.335- KILO',
 '0.055- EACH',
 '10.000- LFT',
 '0.200- EACH',
 '8.000- BAG',
 '5.000- BAG',
 '0.500- EACH',
 '5.000- PIECE',
 '96.000- EACH',
 '3.000- SHEET',
 '12.000- EACH',
 '1.000- PC',
 '9.000- EACH',
 '1.000- FT',
 '0.185- KG',
 '0.525- KG',
 '1.830- KG',
 '3.040- KG',
 '1.450- KG',
 '1.990- KG',
 '0.080- KG',
 '0.190- EACH',
 '1.200- EACH',
 '1.000- BAG',
 '3.000- BAG',
 '16.000- PIECE',
 '10.000- SHEET',
 '21.000- LF',
 '4.000- LF',
 '0.145- EACH',
 '10.000- EACH',
 '24.000- EACH',
 '15.000- PC',
 '5.000- PC',
 '0.140- KG',
 '14.000- EACH',
 '0.415- KG',
 '0.515- KG',
 '0.335- KG',
 '1.010- KG',
 '0.320- KILO',
 '0.545- KG',
 '0.630- KILO',
 '0.285- KILO',
 '20.000- EACH',
 '16.000- LF',
 '28.000- LF',
 '31.000- LF',
 '50.000- LF',
 '8.000- LF',
 '1,200.000- EACH',
 '250.000- LF',
 '0.005- EACH',
 '2.250- KG',
 '3.755- KG',
 '0.700- EACH',
 '0.315- EACH',
 '1.320- EACH',
 '0.600- EACH',
 '0.090- KILO',
 '4.000- BAG',
 '6.000- BAG',
 '9.000- PIECE',
 '4.500- EACH',
 '264.000- LF',
 '33.000- EACH',
 '3.325- EACH',
 '0.835- KG',
 '0.145- KG',
 '1.665- EACH',
 '2.380- EACH',
 '1.360- KG',
 '1.310- EACH',
 '0.905- EACH',
 '0.140- KILO',
 '100.000- EACH',
 '1.000- BNDL',
 '13.000- EACH',
 '14.000- LF',
 '60.000- EACH',
 '4.000- SHEET',
 '0.050- EACH',
 '14.000- PC',
 '0.015- EACH',
 '0.085- KG',
 '1.570- KG',
 '0.385- KG',
 '0.985- KG',
 '0.150- KILO',
 '0.830- KG',
 '0.290- EACH',
 '0.230- EACH',
 '0.045- KILO',
 '0.135- KILO',
 '0.303- KILO',
 '0.058- KILO',
 '61.000- PIECE',
 '13.000- PIECE',
 '6.000- LF',
 '335.000- EACH',
 '18.000- EACH',
 '24.000- PC',
 '0.170- EACH',
 '8.000- TUBE',
 '5.208- KG',
 '0.805- KG',
 '2.465- KG',
 '1.120- KG',
 '0.950- KG',
 '0.400- KILO',
 '0.330- EACH',
 '0.320- EACH',
 '0.420- EACH',
 '0.875- EACH',
 '0.110- KILO',
 '0.080- KILO',
 '0.050- KILO',
 '0.050- KG',
 '30.000- LFT',
 '1.000-',
 '7.000- BAG',
 '18.000- PIECE',
 '12.000- LF',
 '2.000- PC',
 '0.250- EACH',
 '0.530- KG',
 '0.720- KG',
 '0.535- KG',
 '0.415- KILO',
 '12.000- LFT',
 '8.000- LFT',
 '16.000- BAG',
 '1.500- EACH',
 '16.000- FOOT',
 '64.000- LF',
 '24.000- LF',
 '10.000- PC',
 '0.105- KG',
 '4.430- KG',
 '1.000- KG',
 '1.280- KG',
 '0.680- KG',
 '0.070- KG',
 '1.340- KG',
 '0.175- EACH',
 '0.450- EACH',
 '0.040- KILO',
 '2.000- ROLL',
 '19.000- EACH',
 '25.000- EACH',
 '26.000- LF',
 '0.780- EACH',
 '2.590- KG',
 '0.035- KILO',
 '0.220- KILO',
 '50.000- LFT']

In [23]:
year_2022['Quantity'] = year_2022['Quantity'].astype(str)

for row in year_2022['Quantity']:
    for item in to_replace:
        if '-' in item:
            temp = []
            temp.append(item.split(sep='-'))

1,224.000
2,000.000
1,000.000
6,000.000
1,200.000
1,320.000
1,300.000
2,500.000
1,500.000

0        12.000
1         2.000
2         2.000
3         1.000
4         1.000
          ...
85832     1.000
85833     1.000
85834     1.000
85835     1.000
85836     1.000
Name: Quantity, Length: 85837, dtype: object

In [23]:
def spliter(series):
        
    if '-' in series:
        return series.str.split('-')
    else:
        pass

Check link below tomorrow

In [12]:
year_2022[465:466]

,Date,Invoice,SKU,Name,Quantity,QTD,UOM,Total,UOM2
465,2022-01-11,33828B,2410S,2x4-10'KDSPF 2BTR PREMIUM,4.000- PIECE,1,43.33-\r\n,43.33,1

In [13]:
testdf = year_2022

In [23]:
n = 0

for row in testdf:
            
    if '-' in testdf['Quantity'][n]:
        buffer = []
        buffer.append(testdf['Quantity'][n].str.split('-'))
        testdf['QTD'] = buffer[0]
        testdf['UOM2'] = buffer[1]
        n+=1
    else:
        pass

In [25]:
testdf['Quantity'][465]

'4.000- PIECE'

In [11]:
year_2022.insert(5, "QTD", 1)

In [ ]:
https://sparkbyexamples.com/pandas/pandas-split-column/#:~:text=In%20Pandas%2C%20the%20apply(),to%20split%20into%20two%20columns.